### ISSUE TITLE
Has "Share Map" feature ever actually emailed the link to the recipient email?

### ISSUE THREAD

**Issue by MYPAVE** [afixia/mysites-tracker#27]
Mark says it was originally supposed to do this (and that it did in the old version) which makes sense as I have always wondered why the recipient email portion is even there as it does nothing...? 

There should be a "share" button but there never has been, only a copy link button. Can we check on this?

![Screenshot_3](https://user-images.githubusercontent.com/71840246/102528572-5dd3c900-4064-11eb-933d-1ea2c6bee9e3.jpg)

**Comment by galtonafixia** [comment]
The 'Recipient Email' address and the 'Link Expiration' are used to create a security token.  This security token is part of the link that gets copied and which the user will copy and paste into an email.  This gives us a possible way to track the link once it has been emailed out into world and someone uses it to view a "shared map."  The recipient email let's us know who originally received the link, because it's embedded in the encrypted link token.  The 'Recipient Email' address is there as a security measure and not as a recipient of a system generated email.
The share map requirement was not to actually send a system generated email, but to create a secure link with an expiration for the user to send to the customer.

I can add some text on this dialog that explains this for a future reminder. 
If you want the dialog to optionally send a system generated email, we can easily add that feature.
